version: 2

volumes:
  registry_data:
    name: registry_data

networks:
  internal:

services:
  registry:
    image: registry:2
    container_name: registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - registry_data:/var/lib/registry
    networks:
      - internal
    restart: always

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htpasswd-rw:/etc/nginx/conf.d/nginx-rw.htpasswd
      - ./htpasswd-ro:/etc/nginx/conf.d/nginx-ro.htpasswd
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.key:/etc/nginx/conf.d/server.key
      - ./server.crt:/etc/nginx/conf.d/server.crt
    depends_on:
      - registry
    restart: always
    networks:
      - internal